---
dist: xenial

language: python
python:
  - "2.7"

before_install:
  - git clone -b ${lint_version} https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules

install:
  - pip install --upgrade ansible-lint
  - ansible --version

script:
  - ansible-lint -c .ansible-lint `find . -regex ".*\.\(yml\)"`

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
