FROM {{ item.image }}
ENV container docker
RUN yum makecache fast && yum update -y && yum -y install initscripts systemd-sysv redhat-lsb-core sudo bash iproute libselinux-python libsemanage-python python-setuptools \
yum-plugin-ovl && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all;

