---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/yamllint.yml
platforms:
  - name: test-atg-platform-patching-11.2p2
    image: centos:6
    privileged: True
    groups:
      - atg-platform-patching-11.2p2
provisioner:
  name: ansible
  config_options:
    ssh_connection:
      control_path: "/var/ans/%%h"
  env:
    ANSIBLE_LIBRARY:
      /home/gitlab-runner/.local/lib/python2.7/site-packages/epam_ansible
  lint:
    name: ansible-lint
scenario:
  name: docker-11.2p2
verifier:
  name: testinfra
  lint:
    name: flake8
